#!/bin/sh
set -eu

if [ -r /etc/aster/aster.env ]; then
  set -a
  . /etc/aster/aster.env
  set +a
fi

hobot_agent_dir=${HOBOT_CODING_AGENT_DIR:-${ASTER_CODING_AGENT_DIR:-/etc/aster/agent}}
hobot_session_dir=${HOBOT_CODING_AGENT_SESSION_DIR:-${ASTER_CODING_AGENT_SESSION_DIR:-/var/lib/aster/pi-sessions}}
export HOBOT_CODING_AGENT_DIR="$hobot_agent_dir"
export HOBOT_CODING_AGENT_SESSION_DIR="$hobot_session_dir"
export ASTER_CODING_AGENT_DIR="$hobot_agent_dir"
export ASTER_CODING_AGENT_SESSION_DIR="$hobot_session_dir"
export PI_SKIP_VERSION_CHECK="${PI_SKIP_VERSION_CHECK:-1}"

exec /usr/local/lib/aster/hobot "$@"
